seed: 666
data_path: ../input/ultramnistblack
train_batch_size: 16
eval_batch_size: 16
num_workers: 4
max_epochs: 20
train_epoch_length: 100
eval_epoch_length: 100
lr: 0.00001
use_amp: false
debug: false
model: resnet18
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 3
output_dir: ./logs
log_every_iters: 2
